name: 小乐
on:
  workflow_dispatch:
  schedule:
     - cron: '1 11 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        BAIDU_COOKIE: ${{ secrets.BAIDU_COOKIE }}
        TZ: Asia/shanghai
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【小乐】'
        if: env.BAIDU_COOKIE
        run: |
          node Task/xiaole.js
        env:
          XL_URL: ${{ secrets.XL_URL }}
          COOKIES_SPLIT: ${{ secrets. COOKIES_SPLIT }}
